Python for Data & Analytics - 2nd Edition<br>
Chapter 10, section 7<br>

*** requires datafile: aqi.txt

In [1]:
import pandas as pd
dfAQI = pd.read_csv('aqi.txt', index_col='color')
dfAQI

                               concern  low  high
color
Green                             Good    0    50
Yellow                        Moderate   51   100
Orange  Unhealthy for Sensitive Groups  101   150
Red                          Unhealthy  151   200
Purple                  Very Unhealthy  201   300
Maroon                       Hazardous  301   999

In [2]:
dfAQI['number'] = [1, 2, 3, 4, 5, 6]

In [3]:
dfAQI

                               concern  low  high  number
color
Green                             Good    0    50       1
Yellow                        Moderate   51   100       2
Orange  Unhealthy for Sensitive Groups  101   150       3
Red                          Unhealthy  151   200       4
Purple                  Very Unhealthy  201   300       5
Maroon                       Hazardous  301   999       6

In [4]:
newrow = \
 pd.DataFrame({'concern':['Worst'],'low':[1000],'high':[9999],'number':7},
              index=['Brown'])
dfAQI = pd.concat([dfAQI, newrow])

In [5]:
dfAQI

                               concern   low  high  number
Green                             Good     0    50       1
Yellow                        Moderate    51   100       2
Orange  Unhealthy for Sensitive Groups   101   150       3
Red                          Unhealthy   151   200       4
Purple                  Very Unhealthy   201   300       5
Maroon                       Hazardous   301   999       6
Brown                            Worst  1000  9999       7

In [6]:
dfAQI.drop('number', axis='columns', inplace=True)
dfAQI

                               concern   low  high
Green                             Good     0    50
Yellow                        Moderate    51   100
Orange  Unhealthy for Sensitive Groups   101   150
Red                          Unhealthy   151   200
Purple                  Very Unhealthy   201   300
Maroon                       Hazardous   301   999
Brown                            Worst  1000  9999

In [7]:
dfAQI.drop('Brown', inplace=True)
dfAQI

                               concern  low  high
Green                             Good    0    50
Yellow                        Moderate   51   100
Orange  Unhealthy for Sensitive Groups  101   150
Red                          Unhealthy  151   200
Purple                  Very Unhealthy  201   300
Maroon                       Hazardous  301   999

In [8]:
dfAQI.at['Orange', 'concern'] = 'Unhealthy For Some'
dfAQI

                   concern  low  high
Green                 Good    0    50
Yellow            Moderate   51   100
Orange  Unhealthy For Some  101   150
Red              Unhealthy  151   200
Purple      Very Unhealthy  201   300
Maroon           Hazardous  301   999

Code from: Python for Data & Analytics, (c) 2025 Rose River Software, LLC